##### **Objective:** Use Pandas and NumPy to clean, slice, and query retail data to find high-performing products.

In [1]:
#List Data Structures 
products = ['Widget A', 'Widget B', 'Gadget X', 'Gadget Y', 'Tool Z']

units_sold = [12, 15, 7, 20, 10, 14, 18, 5, 22, 11, 13, 16, 8, 21, 9, 12, 15, 7, 20, 10, 14, 18, 5, 22, 11, 13, 16, 8, 21, 9]

regions = ['North', 'South', 'East', 'West', 'North', 'South']

sales = [120.5, 150.0, 70.2, 200.8, 100.0, 140.5, 180.0, 50.2, 220.8, 110.0, 130.5, 160.0, 80.2, 210.8, 90.0, 120.5, 150.0, 70.2, 200.8, 100.0, 140.5, 180.0, 50.2, 220.8, 110.0, 130.5, 160.0, 80.2, 210.8, 90.0] 

cogs = [80.0, 90.0, 40.0, 120.0, 60.0, 85.0, 95.0, 45.0, 130.0, 65.0, 82.0, 92.0, 42.0, 125.0, 62.0, 80.0, 90.0, 40.0, 120.0, 60.0, 85.0, 95.0, 45.0, 130.0, 65.0, 82.0, 92.0, 42.0, 125.0, 62.0]

discounts = [5.0, 10.0, 2.0, 15.0, 0.0, 5.0, 10.0, 2.0, 15.0, 0.0, 5.0, 10.0, 2.0, 15.0, 0.0, 5.0, 10.0, 2.0, 15.0, 0.0, 5.0, 10.0, 2.0, 15.0, 0.0, 5.0, 10.0, 2.0, 15.0, 0.0]

In [2]:
print(len(products))
print(len(units_sold))
print(len(regions))
print(len(sales))
print(len(cogs))
print(len(discounts))

5
30
6
30
30
30

In [3]:
products = products * 6
regions = regions * 5

Calculate profit dynamically: Sales - COGS - Discount profit = [round(s - c - d, 2) for s, c, d in zip(sales, cogs, discounts)]

In [4]:
profit = [round(s - c - d, 2) for s, c, d in zip(sales, cogs, discounts)]
print(profit)

[35.5, 50.0, 28.2, 65.8, 40.0, 50.5, 75.0, 3.2, 75.8, 45.0, 43.5, 58.0, 36.2, 70.8, 28.0, 35.5, 50.0, 28.2, 65.8, 40.0, 50.5, 75.0, 3.2, 75.8, 45.0, 43.5, 58.0, 36.2, 70.8, 28.0]

Merging using NumPy # Note: NumPy arrays usually prefer a single data type.
We can use object type here to accommodate both strings and numbers. data_array = np.column_stack((products, units_sold, regions, sales, cogs, profit, discounts))

In [5]:
import numpy as np
import pandas as pd

In [6]:
array_df = np.column_stack((products, units_sold, regions, sales, cogs, profit, discounts))
print(array_df)

[['Widget A' '12' 'North' '120.5' '80.0' '35.5' '5.0']
 ['Widget B' '15' 'South' '150.0' '90.0' '50.0' '10.0']
 ['Gadget X' '7' 'East' '70.2' '40.0' '28.2' '2.0']
 ['Gadget Y' '20' 'West' '200.8' '120.0' '65.8' '15.0']
 ['Tool Z' '10' 'North' '100.0' '60.0' '40.0' '0.0']
 ['Widget A' '14' 'South' '140.5' '85.0' '50.5' '5.0']
 ['Widget B' '18' 'North' '180.0' '95.0' '75.0' '10.0']
 ['Gadget X' '5' 'South' '50.2' '45.0' '3.2' '2.0']
 ['Gadget Y' '22' 'East' '220.8' '130.0' '75.8' '15.0']
 ['Tool Z' '11' 'West' '110.0' '65.0' '45.0' '0.0']
 ['Widget A' '13' 'North' '130.5' '82.0' '43.5' '5.0']
 ['Widget B' '16' 'South' '160.0' '92.0' '58.0' '10.0']
 ['Gadget X' '8' 'North' '80.2' '42.0' '36.2' '2.0']
 ['Gadget Y' '21' 'South' '210.8' '125.0' '70.8' '15.0']
 ['Tool Z' '9' 'East' '90.0' '62.0' '28.0' '0.0']
 ['Widget A' '12' 'West' '120.5' '80.0' '35.5' '5.0']
 ['Widget B' '15' 'North' '150.0' '90.0' '50.0' '10.0']
 ['Gadget X' '7' 'South' '70.2' '40.0' '28.2' '2.0']
 ['Gadget Y' '20' 'North' '200.8' '120.0' '65.8' '15.0']
 ['Tool Z' '10' 'South' '100.0' '60.0' '40.0' '0.0']
 ['Widget A' '14' 'East' '140.5' '85.0' '50.5' '5.0']
 ['Widget B' '18' 'West' '180.0' '95.0' '75.0' '10.0']
 ['Gadget X' '5' 'North' '50.2' '45.0' '3.2' '2.0']
 ['Gadget Y' '22' 'South' '220.8' '130.0' '75.8' '15.0']
 ['Tool Z' '11' 'North' '110.0' '65.0' '45.0' '0.0']
 ['Widget A' '13' 'South' '130.5' '82.0' '43.5' '5.0']
 ['Widget B' '16' 'East' '160.0' '92.0' '58.0' '10.0']
 ['Gadget X' '8' 'West' '80.2' '42.0' '36.2' '2.0']
 ['Gadget Y' '21' 'North' '210.8' '125.0' '70.8' '15.0']
 ['Tool Z' '9' 'South' '90.0' '62.0' '28.0' '0.0']]

#### Phase 1: Setup & Conversion
* Using the lists created in the previous exercise, your first task is to move from a NumPy array to a Pandas DataFrame.

In [7]:
df = pd.DataFrame(array_df, columns=['Product','Units_Sold','Region','Sales','COGS','Profit','Discount'])
df.head()

    Product Units_Sold Region  Sales   COGS Profit Discount
0  Widget A         12  North  120.5   80.0   35.5      5.0
1  Widget B         15  South  150.0   90.0   50.0     10.0
2  Gadget X          7   East   70.2   40.0   28.2      2.0
3  Gadget Y         20   West  200.8  120.0   65.8     15.0
4    Tool Z         10  North  100.0   60.0   40.0      0.0

In [8]:
numeric_cols = ['Units_Sold','Sales','COGS','Profit','Discount']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)

df.head()

    Product  Units_Sold Region  Sales   COGS  Profit  Discount
0  Widget A          12  North  120.5   80.0    35.5       5.0
1  Widget B          15  South  150.0   90.0    50.0      10.0
2  Gadget X           7   East   70.2   40.0    28.2       2.0
3  Gadget Y          20   West  200.8  120.0    65.8      15.0
4    Tool Z          10  North  100.0   60.0    40.0       0.0

#### Phase 2: Basic Exploration
* Before diving deep, you need to understand the "skeleton" of your data.
* Shape: Use .shape to confirm you still have 30 rows and 7 columns.
* Summary Stats: Use .describe() to find the Mean, Min, and Max for all numerical columns.
* Question: What is the average (mean) profit across all 30 samples?

In [9]:
df.shape

(30, 7)

In [10]:
df.describe().T.round(1)

            count   mean   std   min   25%    50%    75%    max
Units_Sold   30.0   13.4   5.2   5.0   9.2   13.0   17.5   22.0
Sales        30.0  134.3  51.8  50.2  92.5  130.5  175.0  220.8
COGS         30.0   80.9  28.6  40.0  60.5   82.0   94.2  130.0
Profit       30.0   47.0  19.7   3.2  35.7   45.0   63.8   75.8
Discount     30.0    6.4   5.6   0.0   2.0    5.0   10.0   15.0

In [11]:
round(df['Profit'].mean(),2)

np.float64(47.03)

#### Phase 3: Slicing & Dicing (loc vs iloc)
* Participants often get confused between label-based and integer-based indexing. Practice both:
* Integer Slicing (iloc): Extract the first 10 rows and the first 3 columns.
* Label Slicing (loc): Extract rows 5 through 15, but only the Product and Profit columns.
* Specific Selection: Use loc to find the Sales and Region for the 25th sample in the list.

In [12]:
#Integer Slicing (iloc): Extract the first 10 rows and the first 3 columns.
df.iloc[:10,:3]

    Product  Units_Sold Region
0  Widget A          12  North
1  Widget B          15  South
2  Gadget X           7   East
3  Gadget Y          20   West
4    Tool Z          10  North
5  Widget A          14  South
6  Widget B          18  North
7  Gadget X           5  South
8  Gadget Y          22   East
9    Tool Z          11   West

In [13]:
# Label Slicing (loc): Extract rows 5 through 15, but only the Product and Profit columns.
df.loc[5:15,['Product', 'Profit']]

     Product  Profit
5   Widget A    50.5
6   Widget B    75.0
7   Gadget X     3.2
8   Gadget Y    75.8
9     Tool Z    45.0
10  Widget A    43.5
11  Widget B    58.0
12  Gadget X    36.2
13  Gadget Y    70.8
14    Tool Z    28.0
15  Widget A    35.5

In [14]:
# Specific Selection: Use loc to find the Sales and Region for the 25th sample in the list.
df.loc[24, ["Sales", "Region"]]

Sales     110.0
Region    North
Name: 24, dtype: object

#### Phase 4: Advanced Querying
* The .query() function allows you to write filters using a syntax similar to SQL.
* High Volume: Use .query() to find all rows where Units_Sold > 15.
* Loss Leaders: Use .query() to find any rows where Profit < 0.
* Complex Logic: Find all products in the "North" region that had a Discount greater than 0.

In [15]:
# High Volume: Use .query() to find all rows where Units_Sold > 15.
df.query('Units_Sold > 15')

     Product  Units_Sold Region  Sales   COGS  Profit  Discount
3   Gadget Y          20   West  200.8  120.0    65.8      15.0
6   Widget B          18  North  180.0   95.0    75.0      10.0
8   Gadget Y          22   East  220.8  130.0    75.8      15.0
11  Widget B          16  South  160.0   92.0    58.0      10.0
13  Gadget Y          21  South  210.8  125.0    70.8      15.0
18  Gadget Y          20  North  200.8  120.0    65.8      15.0
21  Widget B          18   West  180.0   95.0    75.0      10.0
23  Gadget Y          22  South  220.8  130.0    75.8      15.0
26  Widget B          16   East  160.0   92.0    58.0      10.0
28  Gadget Y          21  North  210.8  125.0    70.8      15.0

In [16]:
# Loss Leaders: Use .query() to find any rows where Profit < 0.
df.query('Profit < 0')

Empty DataFrame
Columns: [Product, Units_Sold, Region, Sales, COGS, Profit, Discount]
Index: []

In [17]:
# Complex Logic: Find all products in the "North" region that had a Discount greater than 0.
df.query('Region == "North" and Discount > 0')

     Product  Units_Sold Region  Sales   COGS  Profit  Discount
0   Widget A          12  North  120.5   80.0    35.5       5.0
6   Widget B          18  North  180.0   95.0    75.0      10.0
10  Widget A          13  North  130.5   82.0    43.5       5.0
12  Gadget X           8  North   80.2   42.0    36.2       2.0
16  Widget B          15  North  150.0   90.0    50.0      10.0
18  Gadget Y          20  North  200.8  120.0    65.8      15.0
22  Gadget X           5  North   50.2   45.0     3.2       2.0
28  Gadget Y          21  North  210.8  125.0    70.8      15.0